### PR TITLE
mcp: allow configuring protocol version

### LINKED ISSUE #2023: Support for MCP version 2024-11-05
LM Studio (and I believe ollama) currently only support version 2024-11-05.

Lightpanda is using MCP version 2025-11-25 which fails to start when using LM Studio.

It would be great if, for compatibility, lightpanda supported MCP 2024-11-05, perhaps with an env var

```
export LIGHTPANDA_MCP_VERSION="2024-11-05"
lightpanda mcp
```

### PR DESCRIPTION
**Pull request by arrufat**
Closes #2023

### CODE REVIEW

File: src/Config.zig [hunk 1]
```diff
@@ -640,18 +656,41 @@ fn parseMcpArgs(
     allocator: Allocator,
     args: *std.process.ArgIterator,
 ) !Mcp {
-    var mcp: Mcp = .{};
+    var result: Mcp = .{};
+    var env_ver: ?[]const u8 = null;
+    var arg_ver: ?[]const u8 = null;
+
+    if (std.posix.getenv("LIGHTPANDA_MCP_VERSION")) |ver| {
```
Comment (karlseguin) [inline src/Config.zig]: Is there a reason to support this for this one parameter and none other?

File: src/Config.zig [hunk 2]
```diff
@@ -188,6 +189,13 @@ pub fn webBotAuth(self: *const Config) ?WebBotAuthConfig {
     };
 }
 
+pub fn mcpVersion(self: *const Config) []const u8 {
```
Comment (karlseguin) [inline src/Config.zig]: I think exposing the enum is generally more useful, e.g. it can be switched on.

File: src/Config.zig (hunk 1 above)
Comment (arrufat) [reply src/Config.zig]: Right, it's the only one. The person who opened the issue suggested it, but I will remove it.
