### PR TITLE
module: report module's evaluation error

### LINKED ISSUE #654: module execution fails silently
When a modules contains a JS error, it isn't correctly reported by the browser and fails silently.

Example with the following HTML:
```html
<!DOCTYPE html>
<html><head></head><body>
    <script type="module">
        console.log("in");
        const a = undefined;
        let b = a.foo;
        console.log("out");
    </script>
</body></html>
```

**expected result**

```
$ zig build run -- fetch  http://127.0.0.1:1234/error.html
info(page): GET http://127.0.0.1:1234/error.html 200
info(console): in
info(page): eval script inline: TypeError: Cannot read properties of undefined (reading 'foo')
```

**current result**
```
$ zig build run -- fetch  http://127.0.0.1:1234/error.html
info(page): GET http://127.0.0.1:1234/error.html 200
info(console): in
```

### PR DESCRIPTION
**Pull request by krichprollsch**
depends on https://github.com/lightpanda-io/zig-v8-fork/pull/71

fix #654

### CODE REVIEW

**Comment by krichprollsch** [comment]
```$ zig build run -- fetch   --dump  http://127.0.0.1:1234/error.html
info(page): GET http://127.0.0.1:1234/error.html 200
info(console): in
info(page): eval module inline: TypeError: Cannot read properties of undefined (reading 'foo')
warning(page): evaljs: error.JsErr
<!DOCTYPE html>
<html><head></head><body>
    <script type="module">
        console.log("in");
        const a = undefined;
        let b = a.foo;
        console.log("out");
    </script>

</body></html>
```

Having the stack trace seems more challenging :thinking: 
It works differently than the `try catch`.

File: src/runtime/js.zig [hunk 1]
```diff
@@ -1133,6 +1142,17 @@ pub fn Env(comptime State: type, comptime WebApis: type) type {
 
         pub const RemoteObject = v8.RemoteObject;
 
+        pub const Exception = struct {
+            inner: v8.Value,
+            scope: *const Scope,
+
+            // the caller needs to deinit the string returned
+            pub fn exception(self: Exception, allocator: Allocator) !?[]const u8 {
```
Comment (karlseguin) [inline src/runtime/js.zig]: Don't think this can actually return null.

**Comment by karlseguin** [comment]
FWIW, I spent at least an hour yesterday trying to figure out why DDG  scripts were silently failing/aborting. I figured they had some global try/catch, or a window.onerror hook or something else that prevent the error from bubbling out. 

I tried this branch, and I'm seeing an `eval module` now, so that should help.
