### PR TITLE
Use ada-url for URL operations in web APIs

### LINKED ISSUE #1111: Invalid URL parsing
While this doesn't fail on Lightpanda:
```js
let a = new URL("://foo.bar/path?query#fragment");
// a.protocol => ":"
```

It fails on Chrome:
```js
let a = new URL("://foo.bar/path?query#fragment");
```
```
VM217:1 Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at <anonymous>:1:5
```

### PR DESCRIPTION
**Pull request by nikneym**
This PR moves #1127's web API changes to this PR. We can swap-in to ada-url in CDP and close the initial PR once that become a necessity.

* Refactors `URL`.
* Refactors `HTMLAnchorElement`.

Closes #1111.

### CODE REVIEW

File: src/browser/html/elements.zig [hunk 1]
```diff
@@ -269,182 +269,183 @@ pub const HTMLAnchorElement = struct {
...
+        return u.get_origin(page);
     }
 
     // TODO return a disposable string
     pub fn get_protocol(self: *parser.Anchor, page: *Page) ![]const u8 {
         var u = try url(self, page);
-        return u.get_protocol();
+        defer u.destructor();
+
+        return page.arena.dupe(u8, u.get_protocol());
```
Comment (karlseguin) [inline src/browser/html/elements.zig]: `call_arena` (if so, applicable in other places too)

File: src/browser/html/elements.zig [hunk 2]
```diff
@@ -269,182 +269,183 @@ pub const HTMLAnchorElement = struct {
...
+            u.clearPort();
         }
 
-        const href = try u.toString(arena);
-        try parser.anchorSetHref(self, href);
+        const href = try u._toString(page);
+        return parser.anchorSetHref(self, href);
     }
 
     // TODO return a disposable string
```
Comment (krichprollsch) [inline src/browser/html/elements.zig]: using the `call_arena` fixes this comment.
```suggestion
```

File: src/browser/html/elements.zig [hunk 3]
```diff
@@ -269,182 +269,183 @@ pub const HTMLAnchorElement = struct {
...
-        const href = try u.toString(arena);
+        const username = if (maybe_username) |username| username else "";
+        try u.set_username(username);
 
-        try parser.anchorSetHref(self, href);
+        const href = try u._toString(page);
+        return parser.anchorSetHref(self, href);
     }
 
     // TODO return a disposable string
```
Comment (krichprollsch) [inline src/browser/html/elements.zig]: using the call_arena fixes this comment.

```suggestion
```

File: src/browser/html/elements.zig [hunk 4]
```diff
@@ -269,182 +269,183 @@ pub const HTMLAnchorElement = struct {
...
-        const href = try u.toString(arena);
+        const password = if (maybe_password) |password| password else "";
+        try u.set_password(password);
 
-        try parser.anchorSetHref(self, href);
+        const href = try u._toString(page);
+        return parser.anchorSetHref(self, href);
     }
 
     // TODO return a disposable string
```
Comment (krichprollsch) [inline src/browser/html/elements.zig]:
```suggestion
```

File: src/browser/html/elements.zig [hunk 5]
```diff
@@ -269,182 +269,183 @@ pub const HTMLAnchorElement = struct {
         if (try parser.elementGetAttribute(@ptrCast(@alignCast(self)), "href")) |href| {
             return URL.constructor(.{ .string = href }, null, page); // TODO inject base url
         }
-        return .empty;
+        return error.NotProvided;
     }
 
     // TODO return a disposable string
```
Comment (krichprollsch) [inline src/browser/html/elements.zig]:
```suggestion
```

File: src/browser/html/elements.zig [hunk 6]
```diff
@@ -269,182 +269,183 @@ pub const HTMLAnchorElement = struct {
...
     pub fn get_origin(self: *parser.Anchor, page: *Page) ![]const u8 {
         var u = try url(self, page);
-        return try u.get_origin(page);
+        defer u.destructor();
+        return u.get_origin(page);
     }
 
     // TODO return a disposable string
```
Comment (krichprollsch) [inline src/browser/html/elements.zig]:
```suggestion
```

File: src/browser/html/elements.zig [hunk 7]
```diff
@@ -269,182 +269,183 @@ pub const HTMLAnchorElement = struct {
...
+        try u.set_protocol(protocol);
 
-        u.uri.scheme = v;
-        const href = try u.toString(arena);
-        try parser.anchorSetHref(self, href);
+        const href = try u._toString(page);
+        return parser.anchorSetHref(self, href);
     }
 
     // TODO return a disposable string
```
Comment (krichprollsch) [inline src/browser/html/elements.zig]:
```suggestion
```

File: src/browser/html/elements.zig [hunk 8]
```diff
@@ -269,182 +269,183 @@ pub const HTMLAnchorElement = struct {
...
-        const href = try u.toString(arena);
-        try parser.anchorSetHref(self, href);
+        defer u.destructor();
+        try u.set_hostname(hostname);
+
+        const href = try u._toString(page);
+        return parser.anchorSetHref(self, href);
     }
 
     // TODO return a disposable string
```
Comment (krichprollsch) [inline src/browser/html/elements.zig]:
```suggestion
```

File: src/tests/url/url.html [hunk 9]
```diff
@@ -76,8 +76,3 @@
   testing.expectEqual("", sk.hostname);
   testing.expectEqual("sveltekit-internal://", sk.href);
 </script>
-
-<script id=invalidUrl>
-  let u = new URL("://foo.bar/path?query#fragment");
```
Comment (krichprollsch) [inline src/tests/url/url.html:81]: what about testing if the error is thrown instead?

File: src/browser/url/url.zig [hunk 10]
```diff
@@ -223,83 +266,113 @@ pub const URL = struct {
...
-        const arena = page.arena;
-        if (self.uri.fragment == null) return try arena.dupe(u8, "");
+    // Setters.
+
+    /// Ada-url don't define any errors, so we just prefer one unified
+    /// `Internal` error for failing cases.
+    const SetterError = error{Internal};
 
-        return try std.mem.concat(arena, u8, &[_][]const u8{ "#", uriComponentNullStr(self.uri.fragment) });
+    // FIXME: reinit search_params?
```
Comment (krichprollsch) [inline src/browser/url/url.zig]: I sounds like we should reset and parse search params too indeed.
