### PR TITLE
Increase MAX_MESSAGE_SIZE

### LINKED ISSUE #676: Playwright example not working on MacOS
Trying to the run the new Playwright support on MacOS https://gist.github.com/krichprollsch/9809bf7dccc6c132ed4b864d9ea39efc but I get the following exception:

```sh
node:internal/modules/run_main:122
    triggerUncaughtException(
    ^

locator.textContent: Target page, context or browser has been closed
Call log:
  - waiting for locator('h1')

    at /Users/mquandalle/lightpanda-test/playwright-demo.js:10:40

Node.js v22.12.0
```

Not sure if there are more verbose debugging options

```
./lightpanda version
fc0281b
```

### PR DESCRIPTION
**Pull request by sjorsdonkers**
Playwright increased the size of their intermediate JS layer, which no longer fit our MAX_MESSAGE_SIZE.
This fixes: https://github.com/lightpanda-io/demo/pull/41

fix #676

### CODE REVIEW

File: src/server.zig [hunk 1]
```diff
@@ -1246,10 +1246,7 @@ test "Client: read invalid websocket message" {
     }
 
     // length of message is 0000 0401, i.e: 1024 * 256 + 1
```
Comment (krichprollsch) [inline src/server.zig]:
```suggestion
    // length of message is 0000 0401, i.e: 1024 * 512 + 1
```
